language: scala
os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
osx_image: xcode8

scala:
  - 2.12.3

jdk:
  - oraclejdk8

script:
  - sbt compile
  - sbt test
