language: java
scala: 2.12.3
os: linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      brew update;
      brew install sbt;
    fi
script: sbt "$SBT_TEST_CMD";

# We explicitly set the matrix to include oraclejdk8 because MacOS X has issues. See comment below
matrix:
  include:
    - jdk: oraclejdk8
      language: scala
      # oraclejdk8 is not yet available.
      # see https://github.com/travis-ci/travis-ci/issues/2316
    - os: osx
      osx_image: xcode8

script:
  - sbt test

sudo: false
cache:
  apt: true
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2

after_success:
  - sh postinstall.sh